import { invoke } from '@tauri-apps/api/core';
import { appDataDir } from '@tauri-apps/api/path';

function extensionForImage(type: string): string {
  switch (type.toLowerCase()) {
    case 'image/jpeg': return 'jpg';
    case 'image/webp': return 'webp';
    case 'image/gif': return 'gif';
    case 'image/avif': return 'avif';
    case 'image/svg+xml': return 'svg';
    default: return 'png';
  }
}

/** Save generated bytes before a provider's temporary image URL expires. */
export async function saveGeneratedImage(blob: Blob, documentPath: string | null): Promise<string> {
  const name = `ai-${crypto.randomUUID()}.${extensionForImage(blob.type)}`;
  const normalizedPath = documentPath?.replace(/\\/g, '/') ?? null;
  const slash = normalizedPath?.lastIndexOf('/') ?? -1;
  const hasDocumentDir = !!normalizedPath && slash >= 0;
  const directory = hasDocumentDir
    ? `${normalizedPath.slice(0, slash)}/images`
    : `${(await appDataDir()).replace(/\/+$/, '')}/image-cache`;
  const path = `${directory}/${name}`;

  const bytes = new Uint8Array(await blob.arrayBuffer());
  let binary = '';
  for (let i = 0; i < bytes.length; i += 8192) {
    binary += String.fromCharCode(...bytes.subarray(i, i + 8192));
  }
  await invoke('write_file_binary', { path, base64Data: btoa(binary) });

  return hasDocumentDir ? `images/${name}` : path;
}
